In [4]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))



NameError: name 'x3' is not defined

In [5]:
print (x2)

[[3 5 2 4]
 [7 6 8 8]]


In [6]:
print (x1)

[5 0 3 3 7 9]


In [19]:
for x in range (2000, 3201) :
    if (x%7 ==0 and ((x//7) % 5) !=0):
        print (x)
    

2002
2009
2016
2023
2037
2044
2051
2058
2072
2079
2086
2093
2107
2114
2121
2128
2142
2149
2156
2163
2177
2184
2191
2198
2212
2219
2226
2233
2247
2254
2261
2268
2282
2289
2296
2303
2317
2324
2331
2338
2352
2359
2366
2373
2387
2394
2401
2408
2422
2429
2436
2443
2457
2464
2471
2478
2492
2499
2506
2513
2527
2534
2541
2548
2562
2569
2576
2583
2597
2604
2611
2618
2632
2639
2646
2653
2667
2674
2681
2688
2702
2709
2716
2723
2737
2744
2751
2758
2772
2779
2786
2793
2807
2814
2821
2828
2842
2849
2856
2863
2877
2884
2891
2898
2912
2919
2926
2933
2947
2954
2961
2968
2982
2989
2996
3003
3017
3024
3031
3038
3052
3059
3066
3073
3087
3094
3101
3108
3122
3129
3136
3143
3157
3164
3171
3178
3192
3199


In [10]:
def reverse(s):
    if len(s) == 0:
        return s
    else:
        return reverse(s[1:]) + s[0]
firstName = input ('Enter your first name: ')   
LastName = input ('Enter your last Name: ')
print (firstName)
print (LastName)
print (reverse(LastName) + ' '+ reverse(firstName))





Enter your first name: SHivnath
Enter your last Name: Tripathy
SHivnath
Tripathy
yhtapirT htanviHS


In [17]:
import math as m

diameter=12


Volume=(4/3) * m.pi * ((diameter/2)**3)
print(Volume)

904.7786842338603


In [10]:
def reverse (s):
    d=len(s)
    str=''
    for i  in range(d):
        t=d-i
        str = str + s[t-1]
    return str

myName= input("My Name: ")
lastName=input ("LastName: ")
print(myName)
print(lastName)
print(reverse(lastName) + ' ' + reverse(myName))

My Name: Shivnath
LastName: Tripathy
Shivnath
Tripathy
yhtapirT htanvihS


In [19]:
str=''
for i in range(6) :
    for y in range(i):        
        str=str+'*'
print (str)

***************


In [21]:
commaSeparatedValues=input("Enter comma separated values: ")
print(commaSeparatedValues)
print (commaSeparatedValues.split(","))


Enter comma separated values: 2,3,4,5,6
2,3,4,5,6
['2', '3', '4', '5', '6']


In [41]:
def trianleSequence(n):
    for i in range(0, n):
        for j in range(0, i+1):
            print("*", end="")
        print("\r")
    for i in range(0, n):
        for j in range(0, n-(i+1)):
            print("*", end="")
        print("\r")  
        
sequenceTraingle=5
trianleSequence(sequenceTraingle)



*
**
***
****
*****
****
***
**
*



In [42]:
def reverse (s):
    d=len(s)
    str=''
    for i  in range(d):
        t=d-i
        str = str + s[t-1]
    return str

reverseInput= input("Reverse the INPUT: ")
print(reverseInput)
print(reverse(reverseInput))

Reverse the INPUT: Hello
Hello
olleH


In [96]:
input="WE, THE PEOPLE OF INDIA, having solemnly resolved to constitute India into a SOVEREIGN, SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC and to secure to all its citizens"
list = input.split(",")
str=''
str1="    "
str2="          "
str3=""
str4=""
str5=""
str6="            "
str9=""
for x in input.split(","):
    if list.index(x) <= 1:
        str=str + x + ','
    elif list.index(x) == 2:
        str1=str1 + x + ',' + "!"
    elif list.index(x) < 5:
        str2=str2 + x + ','
    else:
        str9=x
for z in str9.split():
    if str9.split().index(z) <2:
        str5=str5+z+" "
    else:
        str6=str6+z+" "
str7=str2+" "+str5
str6=str6+":"
print(str)
print(str1)
print(str7)
print(str6)

WE, THE PEOPLE OF INDIA,
     having solemnly resolved to constitute India into a SOVEREIGN,!
           SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC 
            and to secure to all its citizens :
